print("Enter Branch Credentials")
Branch_Id=input("Enter your Branch_Id:")
Branch_Name=input("Enter your Branch_Name:")
Address=input("Enter your Address:")
Telephone=input("Enter your Telephone:")
NoofStaff=input("Enter your No of Staff:")
Headname=input("Enter your Head Name:")
print("Enter monthly revenue")
a=int(input("sales for Jan"))
b=int(input("sales for Feb"))
c=int(input("sales for Mar"))
d=int(input("sales for Apr"))
e=int(input("sales for May"))
f=int(input("sales for Jun"))
g=int(input("sales for Jul"))
h=int(input("sales for Aug"))
i=int(input("sales for Sep"))
j=int(input("sales for Oct"))
k=int(input("sales for Nov"))
l=int(input("sales for Dec"))
total=a+b+c+d+e+f+g+h+i+j+k+l
avg_annual_rev=total/12
print(Branch_Id,Branch_Name,Address,Telephone,NoofStaff,Headname)
print("Total Annual Revenue= Rs",total)
print("Average Yearly revenue= Rs",avg_annual_rev)
print("Enter for which month you want to see Sales:")
print("a-jan b-feb c-mar d-apr e-may f-jun g-jul h-aug i-sep j-oct k-nov l-dec")
choice=str(input("enter month choice"))
if choice==a: print("jan Rev= Rs "+a , )
elif choice==b: print("Feb Rev= Rs "+b)
elif choice==c: print("Mar Rev= Rs "+c)
elif choice==d: print("Apr Rev= Rs "+d)
elif choice==e: print("May Rev= Rs "+e)
elif choice==f: print("Jun Rev= Rs "+f)
elif choice==g: print("Jul Rev= Rs "+g)
elif choice==h: print("Aug Rev= Rs "+h)
elif choice==i: print("Sep Rev= Rs "+i)
elif choice==j: print("Oct Rev= Rs "+j)
elif choice==k: print("Nov Rev= Rs "+k)
elif choice==l: print("Dec Rev= Rs "+l)
else: print("Invalid  Choice")
Staff_id=input("Enter your Stff Id:")
Staff_Name=input("Enter your Staff Name:")
Age=input("Enter your Age:")
Gender=input("Enter ypur Gender:")
CellNo=input("Enter your Cell No:")
Email=input("Enter your Email:")
Branch=input("Enter your Branch:")
Rank=input("Enter your Rank:")
print(Staff_id,Staff_Name,Age,Gender,CellNo,Email,Branch,Rank)
Base_salary=input("Enter staff Base_salary:")
Bonus=input("Enter staff Bonus:")
Deductions=input("Enter staff Deductions:")
sum=Base_salary+Bonus-Deductions
print=("sum")